package practica.ej1.vista;

import practica.ej1.controlador.Controlador;

/**
 *
 * @author aidan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private Controlador control;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Controlador control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        northPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soutPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        altaBtn = new javax.swing.JButton();
        bajaBtn = new javax.swing.JButton();
        modBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        xmlBtn1 = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        finBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EJ1 - Gestión Articulos ACME");

        jPanel1.setLayout(new java.awt.BorderLayout(12, 12));

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanel1.add(eastPanel, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanel1.add(westPanel, java.awt.BorderLayout.LINE_START);

        northPanel.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN DE ARTICULOS ACME");
        northPanel.add(jLabel1);

        jPanel1.add(northPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout soutPanelLayout = new javax.swing.GroupLayout(soutPanel);
        soutPanel.setLayout(soutPanelLayout);
        soutPanelLayout.setHorizontalGroup(
            soutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        soutPanelLayout.setVerticalGroup(
            soutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(soutPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setLayout(new java.awt.GridLayout(7, 0, 4, 4));

        altaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        altaBtn.setText("ALTA");
        altaBtn.addActionListener(this::altaBtnActionPerformed);
        centerPanel.add(altaBtn);

        bajaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bajaBtn.setText("BAJA");
        centerPanel.add(bajaBtn);

        modBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modBtn.setText("MODIFICAR ARTICULO");
        centerPanel.add(modBtn);

        listBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listBtn.setText("LISTADO DE ARTICULOS");
        centerPanel.add(listBtn);

        xmlBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xmlBtn1.setText("EXPORTAR (.xml)");
        centerPanel.add(xmlBtn1);

        exportBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exportBtn.setText("EXPORTAR FICHERO");
        centerPanel.add(exportBtn);

        finBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finBtn.setText("FIN");
        centerPanel.add(finBtn);

        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        // TODO add your handling code here:
        VentanaAlta vAlta = new VentanaAlta (this.control);
        vAlta.setVisible(true);
        vAlta.setLocationRelativeTo(null);
    }//GEN-LAST:event_altaBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaBtn;
    private javax.swing.JButton bajaBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton finBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listBtn;
    private javax.swing.JButton modBtn;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel soutPanel;
    private javax.swing.JPanel westPanel;
    private javax.swing.JButton xmlBtn1;
    // End of variables declaration//GEN-END:variables
}
