/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica.ej1.vista;

import javax.swing.JOptionPane;
import practica.ej1.controlador.Controlador;
import practica.ej1.modelo.Articulo;

/**
 *
 * @author aidan
 */
public class VentanaAlta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAlta.class.getName());
    private Controlador control;

    /**
     * Creates new form VentanaAlta
     */
    public VentanaAlta(Controlador control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        northPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        codLabel = new javax.swing.JLabel();
        codTf = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        descTf = new javax.swing.JTextField();
        precioLabel = new javax.swing.JLabel();
        precioTf = new javax.swing.JTextField();
        stockLabel = new javax.swing.JLabel();
        stockTf = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout(12, 12));

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanel1.add(eastPanel, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jPanel1.add(westPanel, java.awt.BorderLayout.LINE_START);

        northPanel.setLayout(new java.awt.GridLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ALTA ARTICULO");
        northPanel.add(jLabel5);

        jPanel1.add(northPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(southPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.setLayout(new java.awt.GridLayout(5, 2, 6, 6));

        codLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        codLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codLabel.setText("¿Código?");
        centerPanel.add(codLabel);

        codTf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        codTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codTf.setText("Codigo art.");
        centerPanel.add(codTf);

        descLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descLabel.setText("Descripción");
        centerPanel.add(descLabel);

        descTf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        descTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descTf.setText("Desc del art.");
        centerPanel.add(descTf);

        precioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioLabel.setText("Precio");
        centerPanel.add(precioLabel);

        precioTf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        precioTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioTf.setText("Precio del art");
        centerPanel.add(precioTf);

        stockLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLabel.setText("Stock");
        centerPanel.add(stockLabel);

        stockTf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stockTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stockTf.setText("Cantidad");
        centerPanel.add(stockTf);

        guardarBtn.setText("GUARDAR");
        guardarBtn.addActionListener(this::guardarBtnActionPerformed);
        centerPanel.add(guardarBtn);

        cancelarBtn.setText("CANCELAR");
        centerPanel.add(cancelarBtn);

        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
        try {

            // Recoge los datos de los TextField de VentanaAlta
            String cod = codTf.getText();
            String desc = descTf.getText();
            float precio = Float.parseFloat(precioTf.getText());
            int stock = Integer.parseInt(stockTf.getText());

            // Crea el objeto Articuol con esos datos
            Articulo nuevo = new Articulo(cod, desc, precio, stock);

            // Pide al controlador guardar los datos
            if (control.insertarArticulo(nuevo)) {
                JOptionPane.showMessageDialog(this, "Artículo guardado correctamente");
                this.dispose(); // Cierra al terminar
            } else {
                JOptionPane.showMessageDialog(this, "ERROR. El código ya existe o hay un problema con la BD.");
            }

        } catch (Exception e) {

            // Si introducen valores erroneos salta este JOPtionPane
            JOptionPane.showMessageDialog(this, "Por favor, introduce números válidos en Precio y Stock.");
        }

    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel codLabel;
    private javax.swing.JTextField codTf;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descTf;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel northPanel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioTf;
    private javax.swing.JPanel southPanel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextField stockTf;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
